---
- hosts: ec2_dyn_group
  tags: [init]
  become: true
  gather_facts: false
  tasks:
  - apt: name=python-pip state=present
  - shell: "pip install --upgrade pip"
    ignore_errors: true
  - shell: "pip install certbot_dns_route53"
  - shell: AWS_ACCESS_KEY_ID={{ aws_access_key }} AWS_SECRET_ACCESS_KEY={{ aws_secret_key }} certbot certonly --dns-route53 -d {{ cert_common_name }} --email {{ valid_email }} -n --agree-tos
    no_log: true